### ISSUE TITLE
为什么 Vue 没有采用 Concurrent Mode / Time Slicing？

### ISSUE THREAD

**Issue by lsdsjy** [yfd-feer/frontend-reading#29]
https://github.com/vuejs/rfcs/issues/89

知乎讨论：https://www.zhihu.com/question/434791954

**Comment by PeterChen1997** [comment]
刚好在准备本周的分享，感觉分析的确实挺有道理的，本质上来说确实不需要

在 Vue 3 里，通过 AOT 分离了动态和静态节点，更新的效率提升非常明显，再通过缓存方法、静态节点提升等操作，直接就让 update 事件起飞🛫️

对比 React 需要全量 diff 的 VDOM 逻辑，加上 JSX 不好做 AOT，所以选取了 Fiber 来作为问题的解决方案，也不无道理。但是知乎里有人说 “头疼医脚”、“学习成本高”，感觉也没毛病；Dan 说我更在乎初始化性能，不希望携带过多监听事件的“响应式”逻辑影响渲染效率，也没问题，只是不同角度出发，选取更加合适的解决方案罢了

个人感觉 Vue 3 《方向对了》
