### ISSUE TITLE
9 Hard Lessons I Struggled to Learn During My 18 Years as a Software Developer

### ISSUE THREAD

**Issue by highestop** [yfd-feer/frontend-reading#31]
https://medium.com/better-programming/9-hard-lessons-i-struggled-to-learn-during-my-18-years-as-a-software-developer-14f28512f647

翻译：https://mp.weixin.qq.com/s/2G2kt_HL4Vah1XID6CMohA

**Comment by PeterChen1997** [comment]
语言只是工具这个确实，更包括语言上层实现的框架了，本质是工具的工具，所以不要局限于框架，绝对不是坏事
